### ISSUE TITLE
Provide Usage Example

### ISSUE THREAD

**Issue by mokargas** [federicobond/nunjucks-static-loader#1]
Hey there Federico,

Do you have a usage example of how to use this with the html plugin? Trying to evaluate against my requirements

**Comment by federicobond** [comment]
This project never really worked the way I liked, so I abandoned it shortly after. I am not able to provide support for it so I advise you to read the code and fork your own version if you want to use it.

**Comment by mokargas** [comment]
No problem. Thanks Federico
